export const data = {
  "DEL 1: LAGAR": [
    {q:"Vad innehaller SoL och vad finns den till for?",
     a:"⚖️ Socialtjanstlagen (SoL) reglerar kommunernas skyldighet att ge stod och hjalp till invanare som behover det.\n\nSyftar till frivillighet, helhetssyn och att starka den enskildes sjalvstandighet. 🤝"},
    {q:"Vad innehaller HSL och vad finns den till for?",
     a:"🏥 Halso- och sjukvardslagen (HSL) anger mal och krav for halso- och sjukvarden.\n\nVarden ska bedrivas med respekt for alla manniskors lika varde. Regioner ansvarar for halso- och sjukvard."},
    {q:"Vad innehaller LSS och vad finns den till for?",
     a:"♿ Lagen om stod och service till vissa funktionshindrade ger ratt till stod for personer med stora och varaktiga funktionsnedsattningar.\n\nMal: gott liv med delaktighet och sjalvbestammande. 🌟"},
    {q:"Vad innebar Lex Sara?",
     a:"🚨 Skyldigheten att anmala och utreda missforhallanden i socialtjansten och LSS.\n\nAll personal ar skyldig att rapportera. Syftar till att skydda brukare och forbattra kvaliteten. 🛡️"},
    {q:"Vad innebar Lex Maria?",
     a:"⚠️ Halso- och sjukvarden ska utreda och anmala handelser som medffort eller hade kunnat medfora allvarlig vardskada till IVO.\n\nMal: lara av misstag och forhindra upprepning. 📚"},
    {q:"Vad reglerar Offentlighets- och sekretesslagen?",
     a:"🔒 Allmanhetens ratt att ta del av offentliga handlingar, och skyddet av uppgifter om enskildes halsa, ekonomi och personliga forhallanden.\n\nSekretess galler inom halso- och sjukvard och socialtjanst."},
    {q:"Vad reglerar Smittskyddslagen?",
     a:"🦠 Skydda befolkningen mot smittsamma sjukdomar.\n\nReglerar anmalningspliktig smitta, smittspaning, isolering och behandling. Personal har anmalningsplikt for vissa sjukdomar."},
    {q:"Vad innebar delegering och vilka krav finns?",
     a:"📋 En legitimerad yrkesutovare overlater en arbetsuppgift till annan person.\n>> ✅ Mottagaren maste ha kompetens\n>> 📝 Ska vara skriftlig och tidsbegransad (max 1 ar)\n>> 👁️ Deleganten ansvarar for kontroll av att uppgiften utfors ratt"},
    {q:"Ge exempel pa viktiga statliga myndigheter.",
     a:">> 🏛️ Socialstyrelsen – kunskapsstyrning, foreskrifter\n>> 🔍 IVO – tillsyn av vard och omsorg\n>> 💚 Folkhalsmyndigheten – folkhalsa och smittskydd\n>> 💊 Lakemedelsverket – godkanner lakemedel\n>> 💻 E-halsomyndigheten – digitala halsol osningar"},
    {q:"Vad innebar oppenvard och slutenvard?",
     a:"🚶 Oppenvard: patienten besoker varden utan att ligga inne.\nEx: vardcentral, psykiatrimottagning.\n\n🛏️ Slutenvard: patienten ar inlagd och overnatter.\nEx: sjukhusavdelning, IVA, forlossning."},
    {q:"Ge exempel pa yrkesgrupper i vard och omsorg.",
     a:">> 👨‍⚕️ Lakare, sjukskoterska, underskoterska\n>> 🏃 Fysioterapeut, arbetsterapeut\n>> 🧠 Psykolog, kurator, logoped, dietist\n>> 👶 Barnmorska, biomedicinsk analytiker"},
    {q:"Forklara: helhetssyn, tillganglighet, kontinuitet, KASAM, salutogent forhallningssatt.",
     a:">> 🌍 Helhetssyn – se hela manniskan: fysiskt, psykiskt, socialt, andligt\n>> 🚪 Tillganglighet – vard ska vara latt att na for alla\n>> 🔄 Kontinuitet – samma personal och sammanhangande vard over tid\n>> 🔗 KASAM – Begriplighet + Hanterbarhet + Meningsfullhet\n>> 🌱 Salutogent – fokus pa friskfaktorer och resurser"},
    {q:"Vad innebar folkhalsa och vilka ar malen?",
     a:"💚 Folkhalsa = hela befolkningens halsotillstand.\n\n🇸🇪 Nationellt: jamlik halsa och goda livsvillkor for alla.\n🌍 Internationellt: WHOs mal om halsa for alla, Agenda 2030."},
    {q:"Vilka ar de vanligaste folksjukdomarna?",
     a:">> ❤️ Hjart-karlsjukdomar\n>> 🎗️ Cancer\n>> 🍬 Diabetes typ 2\n>> 😔 Psykisk ohalsa (depression, angst)\n>> 🫁 KOL, allergi/astma, reumatiska sjukdomar"},
    {q:"Forklara friskfaktorer och riskfaktorer.",
     a:"✅ Friskfaktorer: god somn, fysisk aktivitet, socialt stod, meningsfullt arbete, bra kost.\n\n❌ Riskfaktorer: rokning, alkohol, stillasittande, stress, dalig kost, overvikt, ensamhet."},
    {q:"Forklara KASAM och hur det forklarar halsa.",
     a:"🔗 KASAM = Kansla Av SAMmanhang (Aaron Antonovsky).\n>> 🧩 Begriplighet – forsta sin situation\n>> 💪 Hanterbarhet – ha resurser att klara det\n>> 💡 Meningsfullhet – kanna att det ar vart att engagera sig\n\nHog KASAM = battre halsa och motstandskraft mot stress. 🛡️"},
    {q:"Vad ar skillnaden mellan etik och moral?",
     a:"🤝 Moral: de faktiska varderingar och normer som styr ens handlande i praktiken.\n\n🤔 Etik: den vetenskapliga och filosofiska reflektionen av moral – 'vad ar ratt?' pa ett systematiskt plan."},
    {q:"Vilka ar de 4 etiska grundprinciperna?",
     a:">> 🗽 Autonomiprincipen – respektera patientens sjalvbestammande\n>> 💚 Godhetsprincipen – gora gott for patienten\n>> 🚫 Icke-skadaprincipen – undvika att skada\n>> ⚖️ Rattviseprincipen – behandla lika och fordela rattvist"},
    {q:"Vad innebar ett etiskt dilemma? Ge exempel.",
     a:"💭 Situation dar etiska principer konfliktar utan ett sjalvklart ratt svar.\n\n>> 🩸 Patient vagrar blodtransfusion av religiosa skal (autonomi vs godhet)\n>> 🚶 Dement patient vill ga ut ensam (autonomi vs sakerhet)"},
    {q:"Forklara valfardsteknik och e-halsa.",
     a:"🤖 Valfardsteknik: digital teknik som stodjer aldre/funktionsnedsatta att leva sjalvstandigt.\nEx: GPS-larm, robotdammsugare, lakemedelspaminnare.\n\n💻 E-halsa: digitala verktyg i sjukvard – digitala journaler, videobesok, sjalvmonitorering."},
  ],
  "DEL 2: SJUKDOMAR": [
    {q:"Vilka symtom kan man ha vid en fraktur?",
     a:"🦴 Tecken pa fraktur:\n>> 😣 Smarta och omhet pa platsen\n>> 🫧 Svullnad och blamarke\n>> 📐 Felstallning/deformitet\n>> 🔒 Rorelseinskrankning\n>> 🔊 Krepitationer (knastrande ljud)\n>> 🦵 Hoftnara: benet forkortat och utatoroterat"},
    {q:"Vad ar symtom for artros, osteoporos och vad ar skillnaden?",
     a:"🦴 Artros: ledvark (varre vid rorelse), stelhet, knappningar, svullnad. Vanligast i kna, hoft, hander.\n\n🫙 Osteoporos: tyst sjukdom utan symtom forran fraktur uppstar. Kotkompressioner ger ryggsmarta och minskad langd."},
    {q:"Vad ar skillnaden mellan objektiva och subjektiva symtom?",
     a:"💭 Subjektiva: upplevelser bara patienten kanner – smarta, illamaende, yrsel, trotthet.\n\n📏 Objektiva: observerbara eller matbara fynd – feber (matt), svullnad, blodtryck, andningsljud."},
    {q:"Forklara inspektion, auskultation och palpation.",
     a:">> 👁️ Inspektion: se – betrakta utseende, rorelser, hud, hallning\n>> 👂 Auskultation: lyssna – med stetoskop pa hjarta, lungor, tarmljud\n>> 🖐️ Palpation: kanna – trycka pa kroppen for att bedoma organstorlek, omhet, resistenser"},
    {q:"Vilka symtom far du vid hjartinfarkt?",
     a:"❤️‍🔥 Tecken pa hjartinfarkt:\n>> 💢 Ihallande tryck/klamkansla i brostet (>20 min)\n>> 💪 Smarta stralar till arm, kake, rygg, hals\n>> 🤢 Illamaende, kallsvett, blekhet\n>> 😮‍💨 Andnod, angest\n>> ⚠️ Kvinnor: atypiska symtom (trotthet, magont)"},
    {q:"Vilka symtom far du vid karlkramp? Skillnad mot infarkt?",
     a:"💔 Karlkramp: brostsmarta vid anstrangning/kyla, forsvinner inom 15 min med vila eller nitroglycerin.\n\n❤️‍🔥 Hjartinfarkt: smarta kvarstaar >20 min, forsvinner INTE med vila. Hjartmuskel skadas permanent."},
    {q:"Vilka symtom far du vid hjartsvikt?",
     a:"💔 Tecken pa hjartsvikt:\n>> 😮‍💨 Andnod vid anstrangning och liggande (ortopne)\n>> 🦵 Odem i ben och anklar\n>> 😴 Trotthet, orkesloshet\n>> 😮 Nattlig hosta\n>> ⚖️ Viktokni ng (vatskereention)"},
    {q:"Vilka symtom far du vid DVT?",
     a:"🩸 DVT: Smarta, svullnad, rodnad och varme i underbenet.\n\n⚠️ Risk: blodpropp kan lossna – lungemboli – plotslig andnod, brostsmarta, hemoptys."},
    {q:"Vilka symtom tyder pa lunginflammation (pneumoni)?",
     a:"🫁 Symtom: hog feber, frossa, hosta med slem, andnod, brostsmarta, trotthet.\n\n👴 Aldre: ofta forvirring, trotthet, aptitloshet – atypiska symtom!\n\n🔄 Viktig atgard: regelbunden lageskandring for att underlatta sekretdranage."},
    {q:"Vilka symtom vid KOL?",
     a:"🫁 Tecken pa KOL:\n>> 😮 Kronisk hosta med slem (morgonhosta)\n>> 😮‍💨 Andnod vid anstrangning (okar successivt)\n>> 🎵 Pipande andning\n>> 🤒 Frekventa luftvagsinfektioner\n\n🚬 Orsakas nast an alltid av rokning."},
    {q:"Vilka symtom far du vid lungodem?",
     a:"🚨 AKUT – livshotande tillstand! Ring 112!\n\nPlötslig svar andnod, rosslande andning, angest, blaaktig hudton, hosta med rosa skum. Patienten sitter rakt upp for att kunna andas."},
    {q:"Vilka symtom far du vid stroke? Beskriv AKUT-testet.",
     a:"🧠 AKUT-testet:\n>> 😶 A – Ansikte hanger/sned mun\n>> 💪 K – Kraftloshet i arm/ben\n>> 🗣️ U – Uttal svart/forvirrad\n>> ⏱️ T – Tid – ring 112 direkt!\n\nAven: plotslig huvudvark, synbortfall, balansproblem."},
    {q:"Vilka ar de vanligaste symtomen pa Parkinsons?",
     a:"🧠 Tecken pa Parkinsons:\n>> 🤲 Skakningar (tremor) i vila\n>> 🪨 Stelhet i muskler (rigiditet)\n>> 🐢 Langsamma rorelser (bradykinesi)\n>> 🤸 Balansproblem och fallrisk\n>> ✍️ Litet skrivet, lag rost, maskansikte"},
    {q:"Vilka symtom far du vid ett epileptiskt anfall?",
     a:"⚡ Grand mal: medvetslosi het, kramper, cyanos, urininkontinens, trotthet efterat.\n\n👁️ Absens: kortvarig franvaro, tomblickt.\n\n🛟 Atgard: hall personen saker, lagg i framsupa sidolage efter anfallet."},
    {q:"Vad ar UVI och vilka symtom?",
     a:"🔬 UVI – urinvagsinfektion:\n>> 🔥 Sveda/smarta vid miktion\n>> 🚽 Tata trangningar\n>> 💧 Grumlig/illaluktande urin\n\n🌡️ Ovre UVI (pyelonefrit): feber, frossa, flanksmarta.\n\n👴 Aldre: ofta forvirring, trotthet, fallrisk – inga klassiska symtom!"},
    {q:"Vilka symtom kan ses vid prostataforstoring och njurinsufficiens?",
     a:"🔬 Prostata: tata trangningar, svag strale, svart att kissa, nattliga miktioner, urinretention.\n\n🫘 Njurinsufficiens: trotthet, odem, hogt blodtryck, illamaende, klada, minskad urinproduktion."},
    {q:"Beskriv smittkedjan och dess delar.",
     a:"🔗 Smittkedjans delar:\n>> 🐛 Smitkalla – det infekterade (manniska, djur, miljo)\n>> 🦠 Smittamne – mikroorganismen\n>> 💨 Smittavag – luft, kontakt, droppar, blod, fekal-oral\n>> 🚪 Smittport – mun, hud, slemhinnor\n>> 🧍 Mottaglig individ\n\n✂️ Bryta ett led = stoppa smittspridning."},
    {q:"Vad ingar i basala hygienrutiner?",
     a:"🧼 Basala hygienrutiner:\n>> 🙌 Handhygien – handtvatt och/eller handdesinfektion\n>> 🧤 Skyddshandskar vid kontakt med blod/kroppsvaetskor\n>> 🥼 Skyddsrock vid risk for kontamination\n>> 😷 Munskydd/visir vid risk for stank\n>> ➡️ Rent till smutsigt – arbeta systematiskt\n>> 🗑️ Korrekt avfallshantering"},
    {q:"Vad innebar resistenta och multiresistenta bakterier?",
     a:"🦠 Resistenta: klarar sig mot antibiotika som normalt dodar dem.\n\n⚠️ Multiresistenta (MRSA, VRE, ESBL): resistenta mot FLERA antibiotika – svar att behandla.\n\n✅ Viktig atgard: ratt antibiotikaanvandning och strikta hygienrutiner."},
    {q:"Beskriv ren saromlaggning och hur man forebygger trycksaar.",
     a:"🩹 Ren saromlaggning: icke-steril teknik, rena handskar, rent material. Anvands vid ytliga kroniska sar.\n\n📍 Trycksaar vanligast: halar, sacrum, hoftkammar, armbagar.\n\n>> 🔄 Lageskandring var 2:e timme\n>> 🛏️ Avlastningsmadras\n>> 🥗 God nutrition\n>> 💆 Hudvard"},
  ],
  "DEL 3: KONTROLLER": [
    {q:"Forklara kontroll av andning – hur och varfor?",
     a:"🫁 Rakna andetag/minut (12–20 = normalt) i 1 minut utan att patienten vet.\n\nObservera djup, rytm, ljud. Avvikelser kan tyda pa infektion, hjartsvikt eller KOL-forsamring."},
    {q:"Forklara temperaturmatning – hur och varfor?",
     a:"🌡️ Mat med termometer (ora, panna, axill, rektalt).\n\n>> ✅ Normal: 36.5–37.5 °C\n>> 🔥 Feber: >38 °C – kan tyda pa infektion\n>> 🥶 Hypotermi: <35 °C\n\nDokumentera matmetod och varde."},
    {q:"Forklara pulskontroll – hur och varfor?",
     a:"❤️ Palpera radialispuls (handleden) i 1 minut. Normal: 60–100 slag/min.\nNotera frekvens, rytm och styrka.\n\n>> 🐢 Bradykardi: <60\n>> 🐇 Takykardi: >100\n>> 〰️ Oregelbunden = arytmi"},
    {q:"Forklara blodtrycksmatning – hur och varfor?",
     a:"💉 Manschett pa overarmen, arm i hjartniva, sitter still 5 min.\n\n>> ✅ Normal: systoliskt 90–140 / diastoliskt 60–90 mmHg\n>> ⬆️ Hypertoni: >140/90\n>> ⬇️ Hypotoni: <90/60\n\nMat bada armarna initialt, dokumentera vilken arm."},
    {q:"Forklara urinprov och blodprov.",
     a:"💧 Urinprov (mitstrale): rengor, lat forsta urinen rinna, samla mitt-urinen.\nKontrollerar nitrater, leukocyter, protein, glukos.\n\n💉 Kapillart blodprov: stickprov i fingertoppar – ex. P-glukos, Hb.\n\n🔬 Venost: nal i ven – CRP, blodstatus, elektrolyter. Mer blod, mer analyser."},
    {q:"Vad ar vitala parametrar och NEWS2?",
     a:"📊 Vitala parametrar: andning, puls, blodtryck, temperatur, saturation, medvetandegrad.\n\n🚨 NEWS2: poangsystem for tidigt identifiera forsamring. Varje parameter ger poang – hog totalpoang = larm och snabb atgard."},
    {q:"Hur beskriver man smarta och vilka fragor bor du stalla?",
     a:"😣 Fragor: Var? Hur lange? Vad utloser/lindrar? Hur intensivt (0–10)?\n\n>> 🔥 Brannande, stickande, dunkande, molande, krampaktig, utstraland e\n>> 😬 Objektiva tecken: ansiktsgrimaser, spanning, okad puls, svettig, blek\n>> 💊 Lindring: lakemedel, lageskandring, varme/kyla, massage, samtal"},
    {q:"Vilka lagar styr dokumentationen och varfor dokumentera?",
     a:"📝 Lagar: Patientdatalagen (PDL), HSL, Patientsaakerhetslagen.\n\nVarfor dokumentera:\n>> 🛡️ Patientsakerhet och kontinuitet\n>> ⚖️ Rattslig sakerhet for personal\n>> 📊 Underlag for uppfoljning och kvalitet\n>> 🔗 Kommunikation mellan vardgivare"},
    {q:"Vad innebar SBAR? Ge exempel.",
     a:"📞 Strukturerat kommunikationsverktyg:\n\n>> 🔴 S – Situation: 'Patient X har feber 39.5 sedan 2h'\n>> 📋 B – Bakgrund: 'KOL-patient, brukar vara pigg'\n>> 🤔 A – Bedomning: 'Misstanker pneumoni'\n>> ✅ R – Rekommendation: 'Behoover lakarbedomning och ev. antibiotika'"},
    {q:"Vad kan symtomen ikterisk, cyanos och rodnad tyda pa?",
     a:">> 💛 Ikterisk (gul hud/ogon): leverproblem, gallvagshinder, hemolys\n>> 🔵 Cyanos (blaaktig hud/lappar): lag syresaturation, hjart-/lungproblem\n>> 🔴 Rodnad: feber, inflammation, infektion, allergisk reaktion"},
    {q:"Vilka observationer kan du gora av huden?",
     a:"👁️ Observera:\n>> 🎨 Farg – rodnad, blekhet, cyanos, ikterus\n>> 🌡️ Temperatur och fuktighet\n>> 🫧 Turgor (elasticitet)\n>> 🩹 Sar, utslag, hematom, klada, svullnad\n\nDokumentera lage, storlek och utseende."},
  ],
  "DEL 4: REHAB": [
    {q:"Ge exempel pa hjalmedel vid synproblem och horselnedsattning.",
     a:"👓 Syn: forstoringsglasogon, talbok, punktskrift, kappvit, ledarhund, forstorande program.\n\n🦻 Horsel: horapparat, teleslinga, bildtelefon, vibrerande vackarklocka.\n\n🧹 Rengora horapparat: torka med mjuk trasa, rengors ljudkanalen med borste, byt batteri. Aldrig i vatten!"},
    {q:"Ge exempel pa forflyttningshjalmedel.",
     a:">> 🦯 Kapp, krycka, rollator\n>> ♿ Rullstol, elrullstol\n>> 🛝 Glidbrada, glidlakan, vandskiva\n>> 🏗️ Lyft: taklift och golvlift\n>> 🎽 Forflyttningsbalt e"},
    {q:"Vad ar syftet med rehabilitering vs habilitering? Egenvard och empowerment?",
     a:">> 🔄 Rehabilitering: aterfa forlorad funktion efter sjukdom/skada\n>> 🌱 Habilitering: hjalpa dem som aldrig haft en funktion att naa basta formaga\n>> 🏠 Egenvard: atgarder patienten gor sjalv pa lakares ordination\n>> 💪 Empowerment: starka individens tro pa sin egen kraft att paverka sin situation"},
    {q:"Forklara de fyra typerna av rehabilitering.",
     a:">> 💼 Arbets-/yrkesinriktad: aterga till arbete, omskolning, arbetsanpassning\n>> 🧠 Psykologisk/psykiatrisk: samtal, KBT, behandling av psykisk ohalsa\n>> 🤝 Social: aterfa social formaga, boende, relationer, delaktighet i samhallet\n>> 🏥 Medicinsk: behandla sjukdom/skada, traning, hjalmedel"},
    {q:"Ge exempel pa statliga myndigheter inom rehabilitering.",
     a:">> 🏛️ Forsakringskassan – samordnar rehab och sjukforsakring\n>> 💼 Arbetsformedlingen – arbetslivsinriktad rehab\n>> 📚 Socialstyrelsen – kunskapsstyrning\n>> ♿ Myndigheten for delaktighet"},
    {q:"Forklara: medfod hjarn skada, forvarvad hjarn skada, roreselnedsattning, AST.",
     a:">> 👶 Medfod hjarn skada: ex. CP (cerebral pares) – uppstar fore/under/strax efter fodseln\n>> 🧠 Forvarvad: stroke, trauma, syrebrist – uppstar efter normal utveckling\n>> 🦽 Rorelsenedsattning: nedsatt formaga att rora/kontrollera kroppen\n>> 🌈 AST: Autismspektrum tillstand – varierad social kommunikation och begransade/repetitiva beteenden"},
    {q:"Vad innebar SIP?",
     a:"🤝 Samordnad individuell plan – upprattas nar en person behover insatser fran bade socialtjanst och halso-/sjukvard.\n\nKoordinerar insatserna, klargar ansvarsfordelning. Gors TILLSAMMANS med personen sa att hen inte hamnar mellan stolarna. 🪑"},
    {q:"Vad star L-ABCDE for och hur kontrollerar du hjarna, hjarta och lungor?",
     a:"🚑 L-ABCDE:\n>> 🩸 L – Livsfarlig blodning\n>> 💨 A – Airway (luftvag)\n>> 🫁 B – Breathing (andning)\n>> ❤️ C – Circulation (cirkulation)\n>> 🧠 D – Disability (medvetande/neurologi)\n>> 👁️ E – Exposure (helhetsbild)\n\n🧠 Hjarna: medvetandegrad, pupiller, motorik.\n❤️ Hjarta: puls, blodtryck, kapillar aterfy llnad.\n🫁 Lungor: andningsfrekvens, saturation, andningsljud."},
    {q:"Vad innebar chock och hur hanterar du blodning?",
     a:"⚠️ Chock: otillracklig organperfusion – blek, kallsvettig, snabb svag puls, lag blodtryck, forvirring.\n\n🩸 Blodning:\n>> 🤏 Liten: tryck direkt mot saret\n>> 🩹 Mattlig: tryckforband, hoj extremiteten\n>> 🚨 Livshotande: ring 112, tourniquet vid extremitetsblodning"},
  ]
}
